# Generated by Django 5.0.1 on 2024-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='haberler',
            name='haber_ozet',
            field=models.CharField(max_length=500, verbose_name='Haber Özeti'),
        ),
        migrations.AlterField(
            model_name='haberler',
            name='haber_resmi',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='Haber Resmi'),
        ),
    ]
